version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - yum install -y docker
      - service docker start
      - docker --version

  pre_build:
    commands:
      - echo "Pulling Docker images..."
      - docker pull swaggerapi/petstore || echo "Failed to pull PetStore image"
      - docker pull tenable/was-scanner:latest

  build:
    commands:
      - echo "Starting PetStore container..."
      - docker run -d --name petstore -e SWAGGER_URL=http://petstore:8080 -e SWAGGER_BASE_PATH=/v2 swaggerapi/petstore
      - echo "Running WAS scan..."
      - docker run -v $(pwd):/scanner -t -e WAS_MODE=cicd -e ACCESS_KEY=${ACCESS_KEY} -e SECRET_KEY=${SECRET_KEY} --link petstore tenable/was-scanner:latest || true
      - echo "Listing files in workspace..."
      - ls $(pwd)

artifacts:
  files:
    - "**/*"

