version: 0.2


phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Instalando dependencias y configuraciones iniciales"

  pre_build:
    commands:
      - echo "Preparando entorno para la ejecución"
      - docker pull swaggerapi/petstore
      - docker pull tenable/was-scanner:latest

  build:
    commands:
      - echo "Ejecutando PetStore en Docker"
      - docker run -d -p 8080:8080 -e SWAGGER_URL=http://petstore:8080 -e SWAGGER_PATH=/v2 --name petstore swaggerapi/petstore
      - echo "Ejecutando análisis WAS con Tenable"
      - docker run -v $(pwd):/scanner -t \
          -e WAS_MODE=cicd \
  
          -e WAS_CONFIG_FILE=./was/tenable_was.conf \
          --link petstore tenable/was-scanner:latest || true

  post_build:
    commands:
      - echo "Limpieza y finalización"
      - docker stop petstore
      - docker rm petstore

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'
  discard-paths: yes
  base-directory: . # Cambia esto según la ubicación de tus resultados

cache:
  paths:
    - '/root/.cache/**/*'


